[project]
name = "password-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.3",
    "streamlit>=1.43.0",
    "streamlit-js-eval>=0.1.7",
]
